
DELIMITER $$

DROP PROCEDURE IF EXISTS `db`.`` $$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ $$
CREATE DEFINER=`sawda`@`%` PROCEDURE ``()
BEGIN







END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$


DELIMITER ;
