//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by app.rc
//
#define IDM_CONNECTION                  0x0010
#define IDD_ABOUT                       100
#define IDD_LOGIN                       101
#define IDD_WARE                        102
#define IDD_UNIT                        103
#define IDD_UNIT_CAT                    104
#define IDD_USER                        105
#define IDD_PASSWORD                    106
#define IDD_PERMIT_EASY                 107
#define IDD_PRICE                       108
#define IDD_RETURN                      109
#define IDD_MY_PASSWORD                 110
#define IDD_PERMIT_ADVANCED             111
#define IDD_SELL                        112
#define IDD_BUY                         113
#define IDD_CHOOSE_WARE                 114
#define IDD_CONNECTION                  115
#define IDD_FIRM                        116
#define IDD_DEBT                        117
#define IDD_CLIENT                      118
#define IDD_REPORT                      119
#define IDD_CONTACT                     120
#define IDD_WARE_CAT                    121
#define IDD_INDENT                      122
#define IDD_RUN_AS                      123
#define IDR_MAIN                        128
#define IDR_WARE                        129
#define IDR_WARE_CAT                    130
#define IDR_UNIT                        131
#define IDR_UNIT_CAT                    132
#define IDR_USER                        133
#define IDR_SELL                        134
#define IDR_BUY                         135
#define IDR_FIRM                        136
#define IDR_CLIENT                      137
#define IDR_INDENT                      138
#define IDR_REPORT                      139
#define IDS_TITLE_OFN_TYPE                   301
#define IDS_TITLE_OFN_FOLDER                   302
#define IDS_TITLE_OFN_FILE                   303
#define IDS_TITLE_OFN_CONTENT                    304

#define IDI_ABOUT_REG                   401
#define IDI_ABOUT_DIS                   402
#define IDI_ABOUT_HOT                   403
#define IDI_WARE_REG                    404
#define IDI_WARE_DIS                    405
#define IDI_WARE_HOT                    406
#define IDI_UNIT_REG                    407
#define IDI_UNIT_DIS                    408
#define IDI_UNIT_HOT                    409
#define IDI_USER_REG                    410
#define IDI_USER_DIS                    411
#define IDI_USER_HOT                    412
#define IDI_NEW_REG                     413
#define IDI_NEW_DIS                     414
#define IDI_NEW_HOT                     415
#define IDI_EDIT_REG                    416
#define IDI_EDIT_DIS                    417
#define IDI_EDIT_HOT                    418
#define IDI_DELETE_REG                  419
#define IDI_DELETE_DIS                  420
#define IDI_DELETE_HOT                  421
#define IDI_PASSWORD_REG                422
#define IDI_PASSWORD_DIS                423
#define IDI_PASSWORD_HOT                424
#define IDI_PERMIT_REG                  425
#define IDI_PERMIT_DIS                  426
#define IDI_PERMIT_HOT                  427
#define IDI_RELOAD_REG                  428
#define IDI_RELOAD_DIS                  429
#define IDI_RELOAD_HOT                  430
#define IDI_SELL_REG                    431
#define IDI_SELL_DIS                    432
#define IDI_SELL_HOT                    433
#define IDI_BUY_REG                     434
#define IDI_BUY_DIS                     435
#define IDI_BUY_HOT                     436
#define IDI_PRICE_REG                   437
#define IDI_PRICE_DIS                   438
#define IDI_PRICE_HOT                   439
#define IDI_SUBMIT_REG                  440
#define IDI_SUBMIT_DIS                  441
#define IDI_SUBMIT_HOT                  442
#define IDI_CLIENT_REG                  443
#define IDI_CLIENT_DIS                  444
#define IDI_CLIENT_HOT                  445
#define IDI_FIRM_REG                    446
#define IDI_FIRM_DIS                    447
#define IDI_FIRM_HOT                    448
#define IDI_INDENT_REG                  449
#define IDI_INDENT_DIS                  450
#define IDI_INDENT_HOT                  451
#define IDI_CONTACT_REG                 452
#define IDI_CONTACT_DIS                 453
#define IDI_CONTACT_HOT                 454
#define IDI_FILL_START_REG              455
#define IDI_FILL_START_DIS              456
#define IDI_FILL_START_HOT              457
#define IDI_FILL_STOP_REG               458
#define IDI_FILL_STOP_DIS               459
#define IDI_FILL_STOP_HOT               460
#define IDI_VIEW_REG                    461
#define IDI_VIEW_DIS                    462
#define IDI_VIEW_HOT                    463
#define IDI_REPORT_REG                  464
#define IDI_REPORT_DIS                  465
#define IDI_REPORT_HOT                  466
#define IDS_BAD_LOGIN                   501
#define IDS_BAD_TEXT                    502
#define IDS_BAD_SELECT                  503
#define IDS_BAD_CONFIRM_PASSWORD        504
#define IDS_BAD_OLD_PASSWORD            505
#define IDS_ERR_ON_DELETE               511
#define IDS_ERR_NO_PERMIT               512
#define IDS_ERR_EMPTY_INDENT            513
#define IDS_ERR_TOUCH_ROOT              514
#define IDS_ERR_DELETE_FOREIGN          515
#define IDS_PROMPT_DELETE               521
#define IDS_PROMPT_SUBMIT_DEAL          522
#define IDS_PROMPT_APPLY                523
#define IDS_PROMPT_REUSE                524
#define IDS_PROMPT_SUBMIT_INDENT        525
#define IDS_PROMPT_CONTACT_INFO         526
#define IDS_CONNECTION_MENU             561
#define IDS_STATUS_PANE_NUM             562
#define IDS_STATUS_PANE_SUM             563
#define IDS_COMBOBOX_ALL                564
#define IDS_EMPTY_MESSAGE               565
#define IDS_FORMAT_LOAD_DT              571
#define IDS_FORMAT_LOAD_D               572
#define IDS_FORMAT_LOAD_T               573
#define IDS_FORMAT_CTRL_DT              574
#define IDS_FORMAT_CTRL_D               575
#define IDS_FORMAT_CTRL_T               576
#define IDS_COL_MOMENT                  601
#define IDS_COL_CAT                     602
#define IDS_COL_WARE                    603
#define IDS_COL_UNIT                    604
#define IDS_COL_LOGIN                   605
#define IDS_COL_PRICE                   606
#define IDS_COL_RATIO                   607
#define IDS_COL_NAME                    608
#define IDS_COL_MAIN_UNIT               615
#define IDS_COL_AMOUNT                  617
#define IDS_COL_TOTAL                   618
#define IDS_COL_DEBT                    619
#define IDS_COL_UNIT_CAT                620
#define IDS_COL_DISABLED                621
#define IDS_COL_FIRM                    622
#define IDS_COL_ID                      623
#define IDS_COL_CLIENT                  624
#define IDS_COL_OPERATOR                625
#define IDS_COL_DELIVER                 626
#define ID_PERMIT                       700
#define ID_PERMIT_LIST_WARE             701
#define ID_PERMIT_EDIT_WARE             702
#define ID_PERMIT_DELETE_WARE           703
#define ID_PERMIT_LIST_UNIT             704
#define ID_PERMIT_EDIT_UNIT             705
#define ID_PERMIT_DELETE_UNIT           706
#define ID_PERMIT_LIST_USER             707
#define ID_PERMIT_EDIT_USER             708
#define ID_PERMIT_DELETE_USER           709
#define ID_PERMIT_LIST_FIRM             710
#define ID_PERMIT_EDIT_FIRM             711
#define ID_PERMIT_DELETE_FIRM           712
#define ID_PERMIT_LIST_CLIENT           713
#define ID_PERMIT_EDIT_CLIENT           714
#define ID_PERMIT_DELETE_CLIENT         715
#define ID_PERMIT_REPORT                720
#define ID_PERMIT_BUY                   721
#define ID_PERMIT_SELL_RETURN           722
#define ID_PERMIT_BUY_RETURN            723
#define ID_PERMIT_INDENT                724
#define ID_PERMIT_CONTACT               725
#define ID_PERMIT_PRICE                 726
#define ID_PERMIT_PERMIT                727
#define ID_PERMIT_PASSWORD              728
#define ID_PERMIT_SELL_DEBT             729
#define ID_PERMIT_BUY_DEBT              730
#define ID_PERMIT_SELL                  731
#define IDS_TITLE_NEW                   801
#define IDS_TITLE_EDIT                  802
#define IDS_TITLE_EXPORT                803
#define IDS_TITLE_INVOICE               804
#define IDS_TITLE_CHANGE                805
#define IDS_TITLE_INDENT                806
#define IDS_TITLE_SELL_DEBT             807
#define IDS_TITLE_BUY_DEBT              808
#define IDS_TITLE_SELL_RETURN           809
#define IDS_TITLE_BUY_RETURN            810
#define IDS_TITLE_FORM                 811
#define IDS_ROLE                        900
#define IDS_ROLE_ADMINISTRTOR           901
#define IDS_ROLE_SALES_CLERK            902
#define IDC_EDT_NAME                    1001
#define IDC_EDT_PASSWORD                1002
#define IDC_CMB_CAT                     1003
#define IDC_EDT_RATIO                   1004
#define IDC_BTN_CAT                     1006
#define IDC_CMB_UNIT                    1007
#define IDC_EDT_DEBT                    1008
#define IDC_EDT_CONFIRM_PASSWORD        1009
#define IDC_EDT_FIRST_NAME              1010
#define IDC_EDT_LAST_NAME               1011
#define IDC_EDT_PHONE                   1012
#define IDC_EDT_MOBILE                  1013
#define IDC_EDT_ADDRESS                 1014
#define IDC_LIST                        1015
#define IDC_EDT_PRICE                   1016
#define IDC_EDT_AMOUNT                  1017
#define IDC_CHK_PERCENT                 1018
#define IDC_EDT_OLD_PASSWORD            1019
#define IDC_BTN_ADVANCED                1020
#define IDC_CMB_USER                    1021
#define IDC_EDT_SPEND                   1022
#define IDC_EDT_APPEND                  1023
#define IDC_EDT_WARE                    1025
#define IDC_EDT_TOTAL                   1026
#define IDC_BTN_WARE                    1029
#define IDC_CHK_CALC_AMOUNT             1030
#define IDC_CHK_FREE_PRICE              1031
#define IDC_CMB_WARE_CAT                1032
#define IDC_CMB_UNIT_CAT                1033
#define IDC_BTN_WARE_CAT                1034
#define IDC_BTN_UNIT_CAT                1035
#define IDC_EDT_HOST                    1036
#define IDC_CHK_DISABLED                1037
#define IDC_BTN_PRICE                   1038
#define IDC_CMB_FIRM                    1039
#define IDC_BTN_FIRM                    1040
#define IDC_BTN_APPLY                   1042
#define IDC_CMB_CLIENT                  1043
#define IDC_BTN_CLIENT                  1044
#define IDC_EDT_UNIT                    1045
#define IDC_EDT_COMMENT                 1046
#define IDC_DATE_FROM                   1047
#define IDC_DATE_TO                     1048
#define IDC_TIME_FROM                   1049
#define IDC_TIME_TO                     1050
#define IDC_BTN_LIST                    1053
#define IDC_EDT_LOGIN                   1054
#define IDC_DATE_DELIVER                1055
#define IDC_STC_INFO                    1056
#define IDC_STC_FORM                    1057
#define ID_DESK_FIRST                   32801
#define ID_DESK_LAST                    32899
#define ID_VIEW_RELOAD                  32901
#define ID_DATA_MY_PASSWORD             32902
#define ID_DATA_NEW                     32903
#define ID_DATA_EDIT                    32904
#define ID_DATA_DELETE                  32905
#define ID_DATA_PRICE                   32906
#define ID_DATA_PASSWORD                32907
#define ID_DATA_PERMIT                  32908
#define ID_DATA_SUBMIT                  32909
#define ID_DATA_SELL_DEBT               32910
#define ID_DATA_BUY_DEBT                32911
#define ID_DATA_CONTACT                 32912
#define ID_DATA_FILL                    32913
#define ID_DATA_STOP_FILL               32914
#define ID_DATA_SELL_RETURN             32915
#define ID_DATA_BUY_RETURN              32916
#define ID_DATA_VIEW                    32917
#define ID_DATA_EXPORT                  32918
#define ID_DATA_REPORT                  32919
#define ID_DELETE_TEMP_FILE             32920

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         33006
#define _APS_NEXT_CONTROL_VALUE         2001
#define _APS_NEXT_SYMED_VALUE           301
#endif
#endif
